include:
  - board: nice_nano_v2
    shield: tuball_right

  - board: nice_nano_v2
    shield: tuball_left
   
  - board: nice_nano_v2
    shield: tuball_dongle
#    snippet: studio-rpc-usb-uart
    snippet: zmk-usb-logging
#    cmake-args: -DCONFIG_ZMK_STUDIO=y

  - board: nice_nano_v2
    shield: settings_reset
 