include:
  - board: nice_nano_v2
    shield: thumbsup_trackball

  - board: nice_nano_v2
    shield: thumbsup_keyboard
   
  - board: nice_nano_v2
    shield: thumbsup_dongle
# Logging is incompatible with ZMK.Studio - won't compile if both are specified. 
#    snippet: zmk-usb-logging
# ZMK.Studio support:
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y

  - board: nice_nano_v2
    shield: settings_reset
 